language: go
go: 
    - '1.3.3'
    - '1.7'
before_script:
    - go vet ./...
install:
    - sudo apt-get update
    - ./scripts/install.sh
    - git clone 'https://github.com/seccomp/libseccomp-golang.git' './vendor/github.com/seccomp/libseccomp-golang/'
    - git -C './vendor/github.com/seccomp/libseccomp-golang/' checkout --detach 1b506fc7c24eec5a3693cdcbed40d9c226cfc6a1
script: ./scripts/run-tests.sh
